const $=id=>document.getElementById(id);let config=null,devices=[],poller=null;
async function req(url,options={}){const r=await fetch(url,{headers:{"Content-Type":"application/json"},...options});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||`请求失败 ${r.status}`);return b}
function toast(msg,error=false){const n=$("toast");n.textContent=msg;n.className=`toast show${error?" error":""}`;clearTimeout(n.t);n.t=setTimeout(()=>n.className="toast",3500)}
function option(select,name,label=name){const o=document.createElement("option");o.value=name;o.textContent=label;select.appendChild(o)}
function fillSelect(id,items,selected,placeholder){const s=$(id);s.innerHTML="";option(s,"",placeholder);items.forEach(d=>option(s,d.name,`${d.name} · ${d.sample_rate} Hz`));if(selected&&!items.some(d=>d.name===selected))option(s,selected,`${selected} · 当前未检测到`);s.value=selected||""}
async function load(){config=await req("/api/config");devices=(await req("/api/devices")).devices;const wasapi=devices.filter(d=>d.host_api.toLowerCase().endsWith("wasapi")&&!d.loopback);fillSelect("microphone",wasapi.filter(d=>d.inputs>0),config.microphone.name,"选择麦克风");fillSelect("virtualPlayback",wasapi.filter(d=>d.outputs>0),config.virtual_playback.name,"选择虚拟播放设备");fillSelect("virtualRecording",wasapi.filter(d=>d.inputs>0),config.virtual_recording.name,"选择虚拟录音设备");$("microphoneDefault").checked=config.microphone.use_default;$("microphone").disabled=config.microphone.use_default;$("threshold").value=config.signal_threshold_dbfs;$("maxDuration").value=config.cloud_max_duration_seconds;$("cloudConfig").textContent=`API Key：${config.api_key_configured?"已配置":"未配置"} · Workspace：${config.workspace_configured?"已配置":"未配置"} · 音色：${config.voice_id||"未配置"}`;$("configPath").textContent=config.config_path;await recordings();}
function payload(){return{microphone_name:$("microphoneDefault").checked?"":$("microphone").value,microphone_use_default:$("microphoneDefault").checked,virtual_playback_name:$("virtualPlayback").value,virtual_recording_name:$("virtualRecording").value,signal_threshold_dbfs:Number($("threshold").value),cloud_max_duration_seconds:Number($("maxDuration").value)}}
async function save(){config=await req("/api/config",{method:"PUT",body:JSON.stringify(payload())});toast(config.validation_error||"配置已保存",Boolean(config.validation_error));return!config.validation_error}
async function validate(){if(!await save())return;const n=$("validationResult");n.className="result neutral";n.textContent="正在校验主配置和三个音频端点…";try{const r=await req("/api/validate",{method:"POST",body:"{}"});n.className="result ok";n.textContent=`链路有效：${r.microphone} → ${r.virtual_playback} → ${r.virtual_recording}`;toast("设备链路校验通过")}catch(e){n.className="result error";n.textContent=e.message;toast(e.message,true)}}
async function routeTest(){if(!await save())return;const b=$("routeTest");b.disabled=true;try{const r=await req("/api/route-test",{method:"POST",body:"{}"});$("routeDetected").textContent=r.ok?"检测到":"未检测到";$("routeLatency").textContent=r.route_latency_ms==null?"—":`${r.route_latency_ms} ms`;$("routePeak").textContent=`${r.peak_dbfs} dBFS`;toast(r.ok?"虚拟声卡路由正常":"没有从虚拟麦克风回录到校准音",!r.ok);await recordings()}catch(e){toast(e.message,true)}finally{b.disabled=false}}
function resetCloudView(){metric("cloudLatency",null,"等待语音");metric("cableLatency",null,"等待云端音频");metric("totalLatency",null,"等待语音");$("streamDot").className="on";$("streamState").textContent="正在连接云端";$("streamBytes").textContent="0 KB";$("cableReturnState").textContent="等待推流";$("sourceText").textContent="等待说话…";$("translationText").textContent="等待翻译…"}
async function startCloud(){if(!await save())return;resetCloudView();try{await req("/api/cloud/start",{method:"POST",body:JSON.stringify({duration_seconds:Number($("maxDuration").value)})});setRunning(true);toast("实时测试已开始：说话后克隆音频会立即写入 CABLE Input")}catch(e){setRunning(false);$("streamDot").className="error";$("streamState").textContent="启动失败";toast(e.message,true)}}
async function stopCloud(){try{await req("/api/cloud/stop",{method:"POST",body:"{}"});toast("实时测试已停止，对照录音已封装")}catch(e){toast(e.message,true)}finally{setRunning(false);await status();await recordings()}}
async function shutdownStation(){if(!window.confirm("关闭后会停止当前测试并释放麦克风、CABLE Input 和 CABLE Output。确定关闭吗？"))return;const b=$("shutdown");b.disabled=true;try{await req("/api/shutdown",{method:"POST",body:"{}"});clearInterval(poller);$("serviceDot").className="";$("serviceState").textContent="测试台已关闭，可以关闭此网页";$("streamState").textContent="设备已释放";toast("测试台已关闭，音频设备已释放")}catch(e){b.disabled=false;toast(e.message,true)}}
function setRunning(v){$("cloudStart").disabled=v;$("cloudStop").disabled=!v;$("runState").textContent=v?"RUNNING":"IDLE";$("runState").className=`pill${v?" on":""}`;document.querySelectorAll(".config-grid input,.config-grid select").forEach(n=>n.disabled=v||(n.id==="microphone"&&$("microphoneDefault").checked))}
function metric(id,value,pending="—"){$(id).textContent=value==null?pending:`${value} ms`}
function renderStream(metrics,running){const bytes=Number(metrics?.cloud_bytes_written||0);const outputStarted=Boolean(metrics?.virtual_output_started);const outputError=metrics?.virtual_output_error;const returned=Boolean(metrics?.cable_return_detected);$("streamBytes").textContent=`${(bytes/1024).toFixed(1)} KB`;if(outputError){$("streamDot").className="error";$("streamState").textContent=`虚拟输出失败：${outputError}`}else if(outputStarted){$("streamDot").className="on pulse";$("streamState").textContent=running?"正在实时写入 CABLE Input":"本次已完成实时写入"}else if(running){$("streamDot").className="on";$("streamState").textContent=bytes>0?"已收到云端音频，等待有效语音块":"正在采集，等待云端克隆音频"}else{$("streamDot").className="";$("streamState").textContent=bytes>0?"测试已停止":"尚未开始"}if(outputError){$("cableReturnState").textContent="未推流，请先处理上方输出错误"}else if(returned){$("cableReturnState").textContent=metrics.virtual_output_to_cable_recording_ms==null?"已检测到回录":`已回录 · ${metrics.virtual_output_to_cable_recording_ms} ms`}else if(outputStarted){$("cableReturnState").textContent="未检测到回录，请检查 CABLE Output"}else{$("cableReturnState").textContent="等待推流"}}
async function status(){try{const wasRunning=!$("cloudStop").disabled;const s=await req("/api/status");setRunning(s.running);$("sourceText").textContent=s.subtitle?.source||"等待说话…";$("translationText").textContent=s.subtitle?.translation||"等待翻译…";metric("cloudLatency",s.metrics?.mic_to_cloud_audio_ms,s.running?"等待云端首音":"—");metric("cableLatency",s.metrics?.cloud_to_virtual_output_ms,s.running?"等待写入":"—");metric("totalLatency",s.metrics?.mic_to_virtual_output_ms,s.running?"等待写入":"—");renderStream(s.metrics,s.running);renderEvents(s.events||[]);if(!s.running&&wasRunning)await recordings()}catch(e){$("serviceDot").className="";$("serviceState").textContent="本地服务已断开"}}
function renderEvents(events){const root=$("events");root.innerHTML="";if(!events.length){root.innerHTML='<div class="empty">等待测试事件…</div>';return}events.slice(-80).reverse().forEach(e=>{const row=document.createElement("div");row.className="event";const vals=[new Date().toLocaleTimeString(),e.component,e.state,e.message||Object.entries(e.counters||{}).map(([k,v])=>`${k}=${v}`).join(" ")||"—"];vals.forEach((v,i)=>{const s=document.createElement("span");s.textContent=v;s.className=e.state==="error"&&i===3?"error":"";row.appendChild(s)});root.appendChild(row)})}
async function recordings(){const r=await req("/api/recordings");const root=$("recordings");root.innerHTML="";if(!r.recordings.length){root.innerHTML='<div class="empty">暂无录音。</div>';return}r.recordings.forEach(x=>{const row=document.createElement("div");row.className="recording";const meta=document.createElement("div");const strong=document.createElement("strong");strong.textContent=x.name;const small=document.createElement("small");small.textContent=`${(x.size_bytes/1024).toFixed(1)} KB · ${x.modified_at}`;meta.append(strong,small);const audio=document.createElement("audio");audio.controls=true;audio.preload="metadata";audio.src=`/recordings/${encodeURIComponent(x.name)}`;const link=document.createElement("a");link.href=audio.src;link.download=x.name;link.textContent="下载";row.append(meta,audio,link);root.appendChild(row)})}
function wire(){$("refreshDevices").onclick=load;$("saveConfig").onclick=save;$("validate").onclick=validate;$("routeTest").onclick=routeTest;$("cloudStart").onclick=startCloud;$("cloudStop").onclick=stopCloud;$("shutdown").onclick=shutdownStation;$("refreshRecordings").onclick=recordings;$("microphoneDefault").onchange=()=>$("microphone").disabled=$("microphoneDefault").checked}
async function boot(){wire();try{await load();$("serviceDot").className="on";$("serviceState").textContent="本地测试服务已连接"}catch(e){toast(e.message,true)}await status();poller=setInterval(status,500)}boot();
